### ISSUE TITLE
Panic in App Engine (Standard Environment)

### ISSUE THREAD

**Issue by andrewwatson** [gorilla/mux#176]
I have a simple Go app that i'm trying to run with mux and when it gets its first HTTP request it panics.

```
2016/07/19 13:23:13 http: panic serving 127.0.0.1:65156: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc82007c580)
	/Users/andy/utils/go_appengine/goroot/src/net/http/server.go:1389 +0xc1
panic(0x5123c0, 0xc82000a070)
	/Users/andy/utils/go_appengine/goroot/src/runtime/panic.go:443 +0x4e9
github.com/gorilla/mux.(*Router).ServeHTTP(0x0, 0x9dd998, 0xc820111380, 0xc82000c460)
	/Users/andy/go/src/github.com/gorilla/mux/mux.go:78 +0x2a
net/http.(*ServeMux).ServeHTTP(0xc820010b10, 0x9dd998, 0xc820111380, 0xc82000c460)
	/Users/andy/utils/go_appengine/goroot/src/net/http/server.go:1910 +0x17d
appengine_internal.handleFilteredHTTP(0x9dd998, 0xc820111380, 0xc82000c460)
	/Users/andy/utils/go_appengine/goroot/src/appengine_internal/api_dev.go:100 +0x44c
net/http.HandlerFunc.ServeHTTP(0x6d1cc8, 0x9dd998, 0xc820111380, 0xc82000c460)
	/Users/andy/utils/go_appengine/goroot/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc82007c480, 0x9dd998, 0xc820111380, 0xc82000c460)
	/Users/andy/utils/go_appengine/goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82007c580)
	/Users/andy/utils/go_appengine/goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/Users/andy/utils/go_appengine/goroot/src/net/http/server.go:2137 +0x44e
INFO     2016-07-19 13:23:13,849 module.py:788] default: "GET / HTTP/1.1" 500 1528
```

from init()
```
	r := mux.NewRouter()
	r.HandleFunc("/dashboard", handleDashboard)
	r.HandleFunc("/", handleCreateForm)
	http.Handle("/", router)
```

it seems like the issue is here: https://github.com/gorilla/mux/blob/master/mux.go#L78 but I can't see why referencing to r.skipClean would not work.

**Comment by elithrar** [comment]
Where is 'router' defined?

**Comment by andrewwatson** [comment]
oh.

**Comment by andrewwatson** [comment]
ok this was totally my fault. i cut and pasted the example code from the mux docs but I didn't notice I had named my router variable "router" instead of "r".   my bad!
